### ISSUE TITLE
Works with NECN?

### ISSUE THREAD

**Issue by bmarron18** [LANDIS-II-Foundation/Extension-Biomass-Insect#10]
Check to make sure this extension runs correctly with NECN succession.

**Comment by bmarron18** [comment]
First round QAQC; Extension-Biomass-Insects DOES NOT work with NECN:

Running NECN Succession ...
Computing shade ...
% done:   0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
          |----|----|----|----|----|----|----|----|----|----|
Progress: +++++++++++++++++++++++++++++++++++++++++++++++++++
Cohort reproduction ...
% done:   0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
          |----|----|----|----|----|----|----|----|----|----|
Progress: +++++++++++++++++++++++++++++++++++++++++++++++++++
Current time: 2
Running Biomass Insects ...
   Processing landscape for Biomass Insect events ...
   Initializing Defoliation Patches...
Internal error occurred within the program:
  Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Landis.Extension.Insects.Outbreak.InitializeDefoliationPatches(IInsect insect)
   at Landis.Extension.Insects.PlugIn.Run()
   at Landis.Model.Run(ExtensionMain extension)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by bmarron18** [comment]
This issue can be closed; Extension-Biomass-Insects DOES work with NECN (see comment section for  Extension-Biomass-Insects Issue #11).
